component: catalogue
params: "DOCUMENTDB:prod.catalogue.mongo,MONGO_URL:prod.docdb.url.catalogue"


#  Environment=DOCUMENTDB={{ lookup('amazon.aws.aws_ssm', '{{env}}.{{component}}.mongo', region='us-east-1')}}
#  Environment=MONGO_URL="{{ lookup('amazon.aws.aws_ssm', '{{env}}.docdb.url.{{component}}', region='us-east-1')}}"